version: "3.8"

services:
  backend:
    image: ${ECR_PUBLIC_URI}/kldd-server:latest
    ports:
      - "8080:8080"
    container_name: spring-app
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    image: redis:alpine
    container_name: kldd-redis
    restart: always
    ports:
      - "6379:6379"