version: "3.8"

services:
  backend:
    image: ${ECR_PUBLIC_URI}/kldd-server:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: spring-app
    restart: always
    environment:
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DB_ROOT_PASSWORD}
  db:
    image: mysql:8.4
    container_name: kldd-db
    restart: always
    environment:
      MYSQL_DATABASE: kldd_db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql